// mypages.js
// 2023-03-01: by fb

exports.genMainPage = function(lista,data, titulo="Lista de pessoas"){
    var pagHTML = `
    <!DOCTYPE html>
        <html>
            <head>
                <meta charset="UTF-8"/>
                <title>About people...</title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
            <header class="w3-container w3-indigo">
                  <h1>${titulo} (${lista.length})</h1>
                </header>
                <div class="w3-bar w3-border w3-light-grey">
                    <a href="http://localhost:7777/pessoas" class="w3-bar-item w3-button w3-hover-indigo">Página inicial</a>
                    <a href="http://localhost:7777/pessoas/sexo" class="w3-bar-item w3-button w3-hover-indigo">Distribuição por sexo</a>
                    <a href="http://localhost:7777/pessoas/desporto" class="w3-bar-item w3-button w3-hover-indigo">Distribuição por desporto</a>
                    <a href="http://localhost:7777/pessoas/profissao" class="w3-bar-item w3-button w3-hover-indigo">Top 10 profissões</a>
                </div>
                <div class="w3-card-4">
                
                <div class="w3-container">
                    <table class="w3-table-all w3-hoverable">
                      <tr class="w3-hover-deep-purple">
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Idade</th>
                        <th>Sexo</th>
                        <th>Cidade</th>
                      </tr>`
    for (let i = 0; i < lista.length; i++) {
        pagHTML+=`<tr class="w3-hover-pink">
                    <td>${lista[i].id}</td>
                    <td><a href="http://localhost:7777/pessoas/${lista[i].id}">${lista[i].nome}</a></td>
                    <td>${lista[i].idade}</td>
                    <td><a href="http://localhost:7777/pessoas/sexo">${lista[i].sexo}</a></td>
                    <td>${lista[i].morada.cidade}</td>
                </tr>`
        
    }
                    
    pagHTML+=`
                    </table>
                </div>
                <footer class="w3-container w3-indigo">
                  <h5>Generated by pessoas-server: ${data}</h5>
                </footer>
                </div>
            </body>
        </html>

    `
    return pagHTML
}



exports.genPeoplePage = function(pessoa,data){
    var pagHTML = `
    <!DOCTYPE html>
        <html>
            <head>
                <meta charset="UTF-8"/>
                <title>About people...</title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">
                <header class="w3-container w3-indigo">
                  <h1>${pessoa.nome}</h1>
                </header>
                <div class="w3-bar w3-border w3-light-grey">
                <a href="http://localhost:7777/pessoas" class="w3-bar-item w3-button w3-hover-indigo">Página inicial</a>
                <a href="http://localhost:7777/pessoas/sexo" class="w3-bar-item w3-button w3-hover-indigo">Distribuição por sexo</a>
                <a href="http://localhost:7777/pessoas/desporto" class="w3-bar-item w3-button w3-hover-indigo">Distribuição por desporto</a>
                <a href="http://localhost:7777/pessoas/profissao" class="w3-bar-item w3-button w3-hover-indigo">Top 10 profissões</a>
            </div>
                <div class="w3-container">
                <p>${pessoa.id}</p>
                <p>${pessoa.nome}</p>
                <p>${pessoa.idade}</p>
                <p>${pessoa.sexo}</p>
                <p>${pessoa.morada.cidade}</p>
                </div>
                <footer class="w3-container w3-indigo">
                  <h5><a href="http://localhost:7777/pessoas">Voltar à página inicial</a></h5>
                </footer>
                </div>
            </body>
        </html>

    `
    return pagHTML
}

exports.genSexDistribPage = function(lista,data){
    var pagHTML = `
    <!DOCTYPE html>
        <html>
            <head>
                <meta charset="UTF-8"/>
                <title>Distribuição por sexo</title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">
                <header class="w3-container w3-indigo">
                  <h1>Distribuição por sexo</h1>
                </header>
                <div class="w3-bar w3-border w3-light-grey">
                <a href="http://localhost:7777/pessoas" class="w3-bar-item w3-button w3-hover-indigo">Página inicial</a>
                <a href="http://localhost:7777/pessoas/sexo" class="w3-bar-item w3-button w3-hover-indigo">Distribuição por sexo</a>
                <a href="http://localhost:7777/pessoas/desporto" class="w3-bar-item w3-button w3-hover-indigo">Distribuição por desporto</a>
                <a href="http://localhost:7777/pessoas/profissao" class="w3-bar-item w3-button w3-hover-indigo">Top 10 profissões</a>
            </div>
                <div class="w3-container">
                    <table class="w3-table-all w3-hoverable">
                      <tr class="w3-hover-deep-purple">
                        <th>Sexo</th>
                        <th>Quantidade</th>
                      </tr>`
    var feminino = 0;
    var masculino = 0;
    var outro = 0;
    for (let i =0; i<lista.length;i++ ){
        if (lista[i].sexo=="feminino") feminino++
        else if (lista[i].sexo=="masculino") masculino++
        else if (lista[i].sexo=="outro") outro++
    }
    pagHTML+=`<tr class="w3-hover-pink">
                    <td>Feminino</td>
                    <td><a href="http://localhost:7777/pessoas/sexo/feminino">${feminino}</a></td>
                </tr>
                <tr class="w3-hover-pink">
                    <td>Masculino</td>
                    <td><a href="http://localhost:7777/pessoas/sexo/masculino">${masculino}</a></td>
                </tr>
                <tr class="w3-hover-pink">
                    <td>Outro</td>
                    <td><a href="http://localhost:7777/pessoas/sexo/outro">${outro}</a></td>
                </tr>`
        
                    
    pagHTML+=`
                    </table>
                </div>
                <footer class="w3-container w3-indigo">
                   <h5><a href="http://localhost:7777/pessoas">Voltar à página inicial</a></h5>
                </footer>
                </div>
            </body>
        </html>

    `
    return pagHTML
}

exports.genSportDistribPage =function(lista,data){
    var pagHTML = `
    <!DOCTYPE html>
        <html>
            <head>
                <meta charset="UTF-8"/>
                <title>Distribuição por desporto</title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">
                <header class="w3-container w3-indigo">
                  <h1>Distribuição por desporto</h1>
                </header>
                <div class="w3-bar w3-border w3-light-grey">
                <a href="http://localhost:7777/pessoas" class="w3-bar-item w3-button w3-hover-indigo">Página inicial</a>
                <a href="http://localhost:7777/pessoas/sexo" class="w3-bar-item w3-button w3-hover-indigo">Distribuição por sexo</a>
                <a href="http://localhost:7777/pessoas/desporto" class="w3-bar-item w3-button w3-hover-indigo">Distribuição por desporto</a>
                <a href="http://localhost:7777/pessoas/profissao" class="w3-bar-item w3-button w3-hover-indigo">Top 10 profissões</a>
            </div>
                <div class="w3-container">
                    <table class="w3-table-all w3-hoverable">
                      <tr class="w3-hover-deep-purple">
                        <th>Desporto</th>
                        <th>Quantidade</th>
                      </tr>`
    counts = {};
    for (var pessoa of lista) {
        var desportos = new Set()
        for (var desporto of pessoa.desportos){
            desportos.add(desporto)
        }
        for (var desporto of desportos){
            if (!counts[desporto]) counts[desporto]=0
            counts[desporto]++
        }
        
    }
    for (var desporto in counts){
        pagHTML+=`<tr class="w3-hover-pink">
        <td>${desporto}</td>
        <td><a href="http://localhost:7777/pessoas/desporto/${desporto}">${counts[desporto]}</a></td>
    </tr>`
    }
                    
    pagHTML+=`
                    </table>
                </div>
                <footer class="w3-container w3-indigo">
                   <h5><a href="http://localhost:7777/pessoas">Voltar à página inicial</a></h5>
                </footer>
                </div>
            </body>
        </html>

    `
    return pagHTML
}

exports.genTop10profissoes =function(lista,data){
    var pagHTML = `
    <!DOCTYPE html>
        <html>
            <head>
                <meta charset="UTF-8"/>
                <title>Distribuição por profissão</title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">
                <header class="w3-container w3-indigo">
                  <h1>Distribuição por profissão</h1>
                </header>
                <div class="w3-bar w3-border w3-light-grey">
                <a href="http://localhost:7777/pessoas" class="w3-bar-item w3-button w3-hover-indigo">Página inicial</a>
                <a href="http://localhost:7777/pessoas/sexo" class="w3-bar-item w3-button w3-hover-indigo">Distribuição por sexo</a>
                <a href="http://localhost:7777/pessoas/desporto" class="w3-bar-item w3-button w3-hover-indigo">Distribuição por desporto</a>
                <a href="http://localhost:7777/pessoas/profissao" class="w3-bar-item w3-button w3-hover-indigo">Top 10 profissões</a>
            </div>
                <div class="w3-container">
                    <table class="w3-table-all w3-hoverable">
                      <tr class="w3-hover-deep-purple">
                        <th>Profissão</th>
                        <th>Quantidade</th>
                      </tr>`
    profissoes = {};
    for (var pessoa of lista) {
        if (!profissoes[pessoa.profissao]) profissoes[pessoa.profissao]=0
        profissoes[pessoa.profissao]++    
    }
    let freqProfissoes = [];
    for (profissao in profissoes) {
        freqProfissoes.push([profissoes[profissao], profissao]);
    } 
    freqProfissoes.sort((a, b) => {
        return b[0] - a[0];
    });
    for (let i=0; i<10; i++){
        pagHTML+=`<tr class="w3-hover-pink">
        <td>${freqProfissoes[i][1]}</td>
        <td><a href="http://localhost:7777/pessoas/profissao/${freqProfissoes[i][1]}">${freqProfissoes[i][0]}</a></td>
    </tr>`
    }
                    
    pagHTML+=`
                    </table>
                </div>
                <footer class="w3-container w3-indigo">
                   <h5><a href="http://localhost:7777/pessoas">Voltar à página inicial</a></h5>
                </footer>
                </div>
            </body>
        </html>

    `
    return pagHTML
}





